os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
      bash docker_quayio_push sae_docs_bridge
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - secure: cfc1ZNe18u22WXnv9jb4wML+LVllzCNfTD66TMfVn0AhKOqLoiqKCSu2bVaOzXlPT1uhcUCzzTRKh+D+IY/WzDQDoGTXdqUSYpkZCZkCF6SlW5fhSLNvHBSh0x+TeggYb9M7ZYZO2Hj4QByelQasoax8/zhkXW7vWjyWKNfjqV+f17SV9ba6xv9uNLK0ZNUlQECrWb4wPKF3m6dTKGeyKdzwL2lf3t7ciSoij7IxxAUKce6Jc0GXEXGlVQnhXWUIneoDOh1VMToHxYdWiK3gNES0iR6nPp+IpRYUlvNRwz2jlSBPKtJLMuRDTOoJs4vYVJCuOHPmf0mdPZttf5MxEGEhtM8V8H6iuOHBmKpCnk0f8VIWEY8Lyo7neE9TRDQ+QjvYuhp+7hNctAUq5AYaz5wWG/ZvWMENR9jxiezCWvbGm5lDRa5lXet5evlwJ8V9d9IUUhsYI+OnyWcbxqKpqvKKj3TgSB3C0HXz7bOSsz9+xvQNpT1FoItmwilvA+G+Xi2WGB0O+yGAb6EnUX+JdlfzMEJ/JidtekcxKQeabwkSevytLlpqF3ACGAKVFvR+KkxOxLOHQ9bd03oSP6bpvvhJIRlEf70fu3F3aRud7AuOckFwDf70qDcqMyLukUGUG0AKqFpryCN79GLS707yfF+H3s9kfRWx8iANvmpYcC4=
  - secure: IZ/G9X3gQJujkJ8/1ECEgBX8BKPLWXHVvColmqKXhWU0g7Oz6Etr3hOFnr0mA/kgeManO9E4mRYkWKwph6SKjLPLD+3o2SPCVTrVpdsw3h9XKR/LJJq3hAvYmaBX7RyhceVNjMKRyI/ZCBUEpZSj8zFIVXABg51nohLlAPfErDl0OgJ++VuTR578WYNR7l5UjsLyWu7wTH7Jy4jCyiV4BPxXYKFjRTUTMPuyhh5apUJ85Eewbnt4rNZBYQZ2HAcMgnsvV/cYM5ztGpwWjjP7GirVkL6x7zMxgnJdy3XLaFYfQ2g0ETs2sG09YSfUyM1fp96vZu4xrxrdFzdaCiEClRx6Y/18LpocWnxyskMTPNxdToG7LCm1ENmcSymBWKyxeUVCjPIXna1enf+ucNsMatlRa8GNTIv6HccHky6rZBOFOP6X//RAaKJvn5hSytsi7Hwrewvozq3Vhah17soXu69P2939tCYflBj0aUu+fOfeKBuT/2AY0ftWNWa2DEqaLvWmYIqjL+W1ZvroowfVAh0ATLxreChmD95XjClrxbgCMErrs69M0obH7VL8iMXUQvZaod1tWCIixIGLzeLitaGQLBdX0dZ0QVLNTfKEF7BDE0vuPOSZ4q2JnSA4FZ+VL2ilzPK1qKWTrcxOHAUGhIfutl7/ZlM7ZNjtjkFTG/c=
  - secure: UafXO+ChEx4IiyX6+LsKEbL76/M1R3WwplT6ORUlQ97sh/uEHSreZrJe0qfRJVXL65fVQ6yEgg3NHHpL9lsD2ajz4uKOHWc7AE7OkUZ1xXBJszXB5Cj5c6D5k/Bsx8c8KBl75J/3f1ZCwY7aE9gJFZgCc0H4B3H3WUypwO9R9n9zLe/5GNk22+64T1r4046fgn6MzilylkCDAJioaDevqdlatDaHtoarYFvcycZQgRBAa8jnD9Vg/r+FvlD84quhS84KXfoL0jP4UQD3LmH8JvyUrXAs89VNN1y92JJzL/sUOLU91UEY7yVXRM/5x6k63EB96P7fNuaG29Gz2vfZ1pmEgaHD/oKV53F5+mSt/QGLE1GDo+z4Zmu81QrjyDeSS2GhuiT+DZIJszSDR3HLzGCuCSnqnAfdtenCdSYEHsVNwL6fEwOQTiWkzCHCoKT+YkGDzc4wxNuhAJOVZC2YOKZkXRkF4a51wcCAEridqD7PJGaVaW30zVfouwioZzTvRjVHQDx5CPxtztMoE/51q6Gc0D1KqUSLJMdgV6BtBPFhXQrrWdUx7rRw5HrLnyNPiXejNjsUjLo45alt6OH2HMWj7bJIzxBYCbKCC4ogpDZ4rzexxz2XnLy6bEwhKC/5xWy1S/Qesgve4XsBODV1QediD5rv9yjWN/Gw1a2bYt4=
  - secure: cSXnW8A4otm6TX4Mt9YJAtB6x5wXswAjbI6qfso4Nv25qFAefFRTssUvqeg4kNl0G6P1Q2n6JXCT4TtwShpqzt9JbkCuxdSdHdseY8Sz3D4m6XhOkb0Tz0H/Lr8MrwVkwAPnujU/OC7Wx4z6mp4IGkIR2RKeQYGsNNSPUa/eAg3KkR5W3lqVo+Z/2JxLyG4Y3kgfNjP+4boq3zh1R/+tETz6H146ueUJgO79R7Z1K6fMGGdmciKhKpn8f0bYJhygt4YJ3XjKlur+TTuUfF5eoU3O9ZGpFzCRC6/YMfvVKQQ37Sm26Vly9aoDH2tQ4jTHHINoIw0IH26Crszm0sy1mu7tj7Xpy+PuXcxbPszrmPW4fufJeAZjG5JFIkuI9DjQX+JZ1MyaXkJ2EiMl0ZjAFijLKSmdIFiCDsQbh/widI2iKJwHb6NiGCfUqg3O4l0i0369BVzRzLlsDHxljS+AooZwXuYEQr6ENXTS3yGZIK+8EnJaTZo/hWPh9ey5aW5irv5r6SAi9TKs1xLdJMNt6GviYZI1+iha2LwFLti/FPiPf2Hby/7TK5eyWy/ndpydlMwE6poK15Crx8wguXUxthiPibGJfEt/NRRNfxlrPxSlYbo3Vr3/ToT8PQ4jgNH26WaZMyPH1RZyuWAnW6+LdViANkZSo20eSnv9v/j73lw=
