os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      bash docker_quayio_push sae-docs-bridge
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: echo "nothing"
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - secure: "pBAbNx0PEXQk/CZyJpE0ObAAr6qpLesPgyC9s2OGqcHtVdmRBftlW+4hDZoKGWxkeYN5N6e/w1UxzT1CahedLsmIi2/HNXJuNIx7NWQKdWEdBzGOSBSz7GzIQCkHamc5rptShfuMNfll9Gm/Kpq7+d4whQYg7vagloDydqKJCgDx9rSCC3wExLREd7jHuQ5gtcAqBxbWAnUJPlQuUdKWFXXWEFiSuuLVY78oEIBO0mTY2abGi4UkCtDzqLw3v5Uz1ph7YqSISAz0i0ce/rtM13U/ADvNdAgS6U2sS56iYhkW1vFhd+PW5QeUaX98bRRq6ZwZDmfoPv7h53uhpFu1TI3uV56X0qZ8aTGKhIUssSh5oMosYdfDe0k8lFepc+hgkZ+HDjgWWvU+zLjT4QndzJhGVTrQEpiV2xhM/Cl+NJI6VQOusUNUFxHLBDQVOJuywkmUo1WlXx2kVvmmwz7IS8xr2KYWq2IxEtMrI11p+cHZQwZ9l4rd2t+nUadkVbKiB/ahv8FcSC+7wTTm8Bn0IrrAazq43eNBwHTjIxbCz+9cze+bUvNnLeD/Cfpqx2vCC1g7Bp39xNhXTntlM5/aFI+SVLjH9CNGyFGn8p6jrHUP36xbTXb4g1RSgDXopTKFE6L6r+NxMY1XfH+IdMvnUkGyo66fKOZx01/fosWbvDw="
  - secure: "jcRvn3Ei31YcUUo6LOAMtJnoxOeKOX1WgtFIuJMz2IznteVGz/iP53SbZphSlVPQG/1Pbzh2DeefgoYdu0G/Mjl2zwDRM1u630A5ZDFteSiIc0R8e9HNg7P+hZolAl6jCG5ifqf72d8OPJOKTUSdjsZ1y/FQq1dFqJbGLl8sWN0hvel/KjZ2YPJhuAtMa3Gpx4kdDfOWTHH2f0bMrQPUq9XCSooroOwf7H1F6TiVe6c40VhhfGBxpgKTNZy79rupOvx+Fy4s226ZkDF9G/bnrjNXX6IsWM0YSvRYkpPMjWVvgseUG1W2qKRY6+de9RpQbKWc9N6Ho8ONJc5865i5IoZ4l0k2FLWsiHSmrSvs8xJ9ePyqiTP25rKuMQ55mBzBj00AlePKZMBIV22DVbc43a6No9rywQqT6ZoJSzpZc6k1UUEJn9QG1cd+i9AZFvVQAzhZLo3vd9KAB6cQ0SDP6CEl6MYX25rL3QhCE8MdoZ31z6AE5QwGCC1KtBq9JNtDi3TZ26as4ReMj3UCaTxyop8zBlXqTtAoWJ31q9r6/lGN06O1PYp7wh1Rj9urDOE8PT5SE9irlUjh7HZQmhYGz6xCazmkSsLIvbkEomSMmyvwXZdy5eI3cSOPlHsItu+s3TRYS7nUAO/DoWTRIU7Y6HoQZP+74LQ0X3LSiOgW7Qw="

