os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - DOCKER_USERNAME=h3brandon
  - QUAYIO_USERNAME=h3brandon
  - secure: "gzVZ0SnnOkx4gKDM3o2CGpp575B+Wqm421HpZb3qanP/qmn5Kd6ywBZVcOSX2ju6QfY7Bh574zH6h08urJl7EVsMCHoOVJVoE1sC9UFTpqo8+4fbAxQS9/aBiPCWRC63Jy1erVlCBVFv9tGXaeruaugDgKYnUtg5r8XEzNwHuTR60bybpYfhiWvbElSta/7dlBtGNI6Bxu0zbnhUhxr3RGahYB6DUaVRz65V2lq0MklnpbkSOjNI8CRPu+Ht/HzSZyf4dkMAqFhBUUQTZ5Vq9Zu/4Hw8DDVX+NMOo7kdA6Ah6HLJOKZbCqKMQq0tSSdiFjsQmpCPazI+gW3S9U60yNkjdG0/LJYd10USM1XXNMk7ecXv6nWbL352OL1iT3OaGUchdRnR1y5jYjgbI8syqArGLpAHPFd2hSGQO28lUybrMs0b5AmoSmbYbITQh7nAQvda5CZeqkrtZcuYc64cgIQfz0GgXO1sSXqo8ggMgUKFOj/ugttp801Sbb/6FihNZZYTsZiUf+YCXyCUFnSy/1qZ7chfWHSJLRlR6GRhsqswddX7vJMlbafzWUswgDjuBfIBGjNFnLqq3ncLh6LwJk2Mg8VxZXPLju0JHCcN001JRbVrsNL8+M1tS1QK9OBIuiM5QKTQonG11q8/KUqftgsOXvgBB5gvQySjPuqGHV8="
  - secure: "eCub2uZkAf2ds+DokFxg4htEUGttotVpvSehIo3T4EIBmsIFqOWOzCqwz3ZpY0lCRcT/RlnbXC2Z322g3/rnSvsbZgDfpa3hKSaSYPE0CuBiITx0/JQYf7ZVGon1S97YQLVSJFZnmh4Z28kGmZ28mfCEqTIwhQZCJcZqwv/wK+noFoWkpoKSy6cUPFPP3188BkM72Iis7kPSy6uoAgfQtM1P0RrDtiu+6C7inseWrPgXb2/6/IPoG/3jHoTS3YM1/Aa891yWJiNuFix+au8Yv3MunjndVjrvXgi8+6luBzvPVcTW4e6X1nytJPpwP83a9I+S5Cmx3Xb6rwAKNKMqyStB4JzJACQajMdtSEe6CMt5XTU2YQLDEQOM/VuUWXvaHTCrFWhnRl/kggjqTjqP2Vn0/W0vi20hE9BmLdrVfdCpRiiD9WIPwlsVlX6muSVxO8SOcNG5s8Vo9TEUt2B2UCiN6W+H1rzHH5eBup4GGV/IcJAkosR6CKpBp0pl04x8toj0HHxK1bhHp9D9z5s8bZzVLE32uXsMoLzmbhrcYqxTfWXohcmNGXYw2xKUjitPfPuE9zgpgUbLF08IBEa4dWsuhfRj43Bdi2s2usMc2JLRL9h/OWKhGWwZNdrzw4lEW0b4fRHK1o91Oyo05LnS3/EqII4isVvQ+Fp8ZFsMJhE="

  
