os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - DOCKER_USERNAME=h3brandon
  - QUAYIO_USERNAME=h3brandon
  - secure: BX7q6GhNRS8YoPQZ2An0HNsvloCD3taqn/DbaJPUjoXmOk/gQJH4o87N9146aqc+WOm0s52DgvquU6sU+obMYstbV2las6hnVoZu+eKoy8xT72EM9gCHAaB2S8sbXyNv8+qp7caY0Bz+Dn4Ym7Fzz//Fl6Qib476QJqVTrqbs19GCIwFXzJ9WFUEQgH8kIYxjYnSo+07S+s8oMoCLQ8jfdjOCWlr967d3MH4NqFuBAoMtBBT7WqEwSnfw94pT6yDjrYqx5uml8X2Aqe5zyWlvL+mz4Rl/OcbRfDAx2gZ7pkJZp6WUk/QoEqBpMCtagJZIJlY3twkFIAIjcNhOmn5ft2YB+FHJ25FsGgT7wVDBABzAYqfzwvNtVuZwOSokF9OmHyamAi5DRGNkZiXhN1PXGUrv0Jx3noycOJuk2xbhAId+fOQHaZxoCAweMPsbYCQY6QDCSeQ2mlSd3pGLe3QlD/O3AkA39EdUzIGx3WPtbMQAsKld89cNbz/fa41N8Ue3jUh5FW6skmbfCLX43q/oQu8voo6EbMnTqImohjtBMz8qnmyCitbM/sgY3Z0BGeMILyoJWGkEvMFFRRrE+6noQWDE0Ya/KGJSQRrrt3l2fa0TkzOuNdfK9cIC+MoUN5rgexJERexIU36Q3jYXfNG9127pcNoH3ddWtsfPftj3pY=
  - secure: CfZJqIG7/0r/O4tbuw8fU8DbyZOUD3UL92ebByeBzPzqNwRFP/g/Yda5EK/PSg0wVNqU3I0pKk+JCE2q7dg5M3KlWqIs1J4FjT76vVdAstYqfpYtKyhD0wdXIrzPZNAx7cmUKlb9xEX1GsfqkqzHQA2NynDw4eDDVmynP9t2A+sLzbIydGRZ3ZHw3ROoyks6XM2nz8FkwXgjmr3AIlGG2FRcGwuUgtDulHCRBbpmL7buF8bczeA1k0MOhqQdgPQKK7awEBdgngL3aBBaXP+XrAjMdXEui+NZ28L6QkBRUgQpJtaPwyj3k/wCZ7ESA2qjsS1RaABHk5G9eUiLbwaAog4qZXlst5wKj77ZlADuFMFuFjzVMZt8LccP0o9Fl2+rfZkGCr4HJaNSy6x2R9sLV43JXGoNlX43YsknscMUIwx+1ZSoMk2YMPjqsWTv6FKPxC5oMJ9aJwfPwGQGl2Cv9YDcxm2rQlWMO+0c5BTzVBzaLdeBczTWlmazMajpavjLMOWmqB3bM4dLH/Iy2xRp/xdveigOudLGSAZ5NZ1qZ3uCd8iS7PoSLnAEgoNmx/XQ5Oso7L5cNkdHO7U1oNKJuCYrXpVKe3qXZ2ZdHGHmkw96hdLOo8ETDOIvh64ccURPqrsvj0fgktwem9+eK2pa+GrF8UQK9XkXxUN6kRYkEUY=
