os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - DOCKER_USERNAME=h3brandon
  - QUAYIO_USERNAME=h3brandon
  - secure: lyo9pLUklBwkCPuOqsV1DVRK7avzFgyNfTgAxr2yHc2EYeb/iAi6DiJ2uW+ojrSPFXkAlvxX8ABDDjdCZ94RcZz3t5n5FGE9uBnR35CqCzs5pz6aYGHiqTi95cMxMZeiGB3vcfIJGVg5oZneWaqfm99STCf9mk6Mz8wCdq3+VREj+636LR0Z/tZAbAUPYf9Um0tLrKwNqSEYt5ICT86WQOuY4UPfnlD0wNP2/WjQ5AKwedD/9CnzDpt4AggOXRBu5zJZSK+KSAV/SlOgKl4tVK2NrfAmwxLXeS+Z+Jy69bjt+YU+uwGA2ZfPp24dsKMPi5Fd3UWZDgGhOsHa/+2eeT4Pru+vUIcgACy944Uh0wwrvNM82mt/RNB7EwVYffOFYGmtva/bgKIeMSGR/xxnFo6JEAqRegrYcj8NsxHB4jvBqIQTOkK7xT/5YvFK2/Pd4wmwvNN9ib3MpSFJGMs/aWViA5pzQacnAB6eE1bYM0Ro2pO6MT1t92vY/tOlZytZF+9fYpdEz1TixXUqA6l2Fvcm9YD72ELnPY+N/COlchSXzSUJCI1SyZ5SWhoRknaMag58ws+PLyETORuYF7L1dsq7yChEApOJUisU/SiMmdCxwehzVbCZvRibDH4IwpvW/1DxlkDDMet//8rveTwRW9Fpj+2Xm3e2Od+9yMF18zM=
  - secure: OUo7qqiPqIgle5/S1mOTojZkix0xxMGzayKIjentbRb6oHhNieZ9mm6oUUNzo4q1/6fE89gj2qYAtLH0T3mNHTULTfAXWyAHC7YSPuSfK7UbS5C/JbL0iSrU6oAWDgpQWXoYUqtkjp+CbHARweruOXUVy2dUQfJCpyobAIZyLSc6feuipfOuzU2ptQTrJ7Z0FbRsiphkh/a1EMrZfc2vIORR//Z33Ux6g36ZdxqLPasOszobBt85rA/6LRdm2KDluFJkmuEFEZklUAtGtsrp3TAucp6goNphomtBzPAg/cAWbLoNL5BhvalKiHdfB6OiOpL9wERiVhkC6iKstI4ZL5Vti5rVd/M03k3THOGq8wUSM0fFyTaEBu8UPIxbTo8gUQjybrpxdcTqz4/i+G+M+eLIZmAHO1NOaP2pMdg2bPYTOLJPuwe/ZJrqHfoHKlnIGzNtX0NG+VP3Xp48MlXGVT77EH/N5j6WqBK5lik8BGMWLEI9jLTNFJc2NbjeRo++jQdcewEZT1eTqqoxgFvplMW/Dccf6PqpijBRZAw+FI2yYsnsPRnzUZ6fg220XuJAv6d5cRbEG5f86TUF3MlxFI8H3CaGV7qUylqXmsfWKh6mH9SLhT/qgVL2L9w3dru6Cklh63dh/6+gpjjmMe8t11bT59ftCfw7g7SmkvWnKUk=
