os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - secure: F1eQC2N67x9JvzUSHFl0fkr3/VgzKJ4flnE7/k5VKfaa1zXjrpwZtyBawyX5lOvMKxHnhc+M0byRsbMejaxCz7QDu1bI/3LcO4M5bELZSWJoRMlbaKt0+UvEzxils5YrhyXkYEYyn/fObAIS3ABOhm6CT5QTIsTjmSGqr3r4+tKenq0J6vBY4WShC+0Ng03kO6KzcptMCTmwlSx7eTDt1Anr0hVxdk25LgGHHn9dfNxxQYdnNdRtdWz0k/qDqrLZ7qM4D21zx5JNboE5XSdIvOw/NVKOF5Bj+oxbpGbCTeqNkcUSgfsMASChljuxsNvyHHqp7eaND8zMaO9bCKucFVxghZjwa1hJH5SSatWIc9lvKCHffscihsCV1dHaPdGuBYWvNyyT3GQg+8zu/q4yU4vujuZOKhuoqgc5kltMzpZRye1lGl/+rtoCHteYyB444JG52bmhfsJPjZ3q2ZsBMOjmIUyTcFJ5XYcrXQOlx7rxMLw4STYqoG9xyGddahR6WZMmRCk6CW5BjEg8+fgdipHdovzdV0X9lX0w9Zucen9gGHUZh58mYFpNnP3jcc0BG2/FvxM74C+N8UxabGYgHzeLT4NV4YQ+RiD+TH7q5/W2diqZHxIDbipHov+pYtPQm1rKU0xQckv4YpbH7OovT7ukmMkzFQSE2wk3NHz3ubw=
  - secure: F6MnUEv2hAes0dv1xgdMV8iq/VMDZob9GEJThvKv2UravGtDP3oChrUvWpH/nVSc7JU8uG/KnXn6rENLZbsV8t81N+AG15cNXVinznBQH0IBnnrbc0xfdZDth+jHn5+4fCk+HRU06LvXdwo9ykwCTBzo9mVey/ztzwNIGjIC3AX/jGrpu2n0O1bKwFtpzN4WMHeCJT2AUA8Kb/sUis3OtQMAyrlXfNDmqMkRY5QMupKlBIE1k9hhXUqKzEU4lbBNtf10haVOSkqcfQeOQdB+ZzxTnVGUnZq4XkZNa2cgpzV22CB/v++lcDkmslZDZaVBh1KpyLSVXMB2EHXtE+qSZlvCU2dnF5Nx48x5mfYSyIUToq9z9Ruh+5EYSphkOX3j/WTSr1YeK7TYLvF9pmE6baLdfOwSpjfXdkEfrq3E+eH9NLBT8KZVoYxS4Eo8Vv15HP1ANlB/MNyycnvMTuUNOT+NUOBZTlTalHeG2fdr2x3yGBIAxW7/KSq0AOYceMQxq5pMxy0mFxvYKfUEIzvqBRwLmPdTaA/Az1PuPO0uuAtvQSEPuiuL8QhvfJ61WdVyWLpvpPUM845h8YJyQlxcOUCpScQkkXO5G8wKHtEPnVZsCf/JP9lNqAoq5tGXhsW7mHSAc/EBn+ESwK2bKLEiBbpaiExH0E+MHZAmsFAy+mc=
  - secure: Cb0ZGfdvBFwwDVKWNA/dllqlAA7cNFz1SLMWu7CsbGMJjdmU5pink3SdBWjtVsQdw6kRJH+FulbTxMk68yAg5uviT4jckxjuZwwEFk4v1i5RYJ5Wk7Wt7Q8Ta9osi0dZ7bLMirHMtjr4rWqySWzPxMAwbv+6nEeCHpeCzB6QhMsKgxMrAqmiwW5+l+SpDmLpfLsHB9XXOvbqdsTJmjkSh+LLWQOKBC2Sy9weY3GXKgCqDO/RO0Ra2R8ZjqjB0w7IOkevlXOd3YTtcQDGSpAwT/c/oJorFwRN9bjNpjwCSWCIG50htcdG4DQY/n4E71C3cK4KYKrwo+3XevbKfBav+Hu30rlOaDromSxxquv6YuNQtGIU/Qc7CMbwP3FphZLLJG8Pv7LPiDyjlRSjGG8BB4hkNyfZocQBWA/6vct864WrOlrhabHDb0PlyTAtC5go8PgeVU0qEBwrt4Gbh5HYpz6AakgckCiDNnX49x91Ap6AJEWfU5D7HAK9Ba8SS90TowzYCwun+P7Orz9LeFrbaiHZ2Oekj4V53Z3n5JezobABguFzwiyHg8KDnGRmuVx67hgBbxp/JMFoprZEkEYg42Z8HuRzCDuKHksuS6VoGtCg541V33SVMB226bNKbEHUPU3K2LVIUPvJXygvW8woIjlB71/lNKxhVbb8qzJ8TWs=
  - secure: Xp6vG6zfcu9+XaFTspgZ/x6F7W4gK7G9VSAZa+IkAeFH3tNQ60CEpUetwhy4E0xoP4WhpGVYUJvaSEZfhFys/8ysxQ4BMlHw07ZvPpP1PlYptXa+Q31Eb/ydyySnP+QhXuN8D2smH4DUlR/76WDkaf9jez8g2d9nv5rMd866YybIIFSfoiItvaklOkaugoiSRjiJ7vAs6KMlOeleK/Lmk0iWQNm4WdHGfVBuU3DRcUk4Lr/9PDN+9I40k0RgWWS54mxlVrXTZkn0G0L+YUzZKD/SVZc+XyDF8YKbNuBVj+tZSluddmSqLnbLymrEHLheLZx/4xer1RPRZIofUzcfKCkEkQaihlbp3OTiswU9ZOjq/wR3kRpdovn0Z8FlHcoqJzHD9GSoHg8lFtjf8iXQPNJ/zws/h0eIAvBDN3e+EBeeZJ8gmfH+9iVMmNW1sU2pmDd3rlauiG/HYn4YWfytfQtQX4QtEBFQ0ZZJoIJI0O9pVFRtOHneZtytGPSjiI/uH6XuhAwOwrxbSSJIyjkSBxFM/MWad01cGaXr9OBXAJlGDqIa6X7/yMyQsZISbVwnindnagSPPkCJuwiR4aFA886yXoLFaK16hV8/Kwod6C+n//vyYvFlL3x8wuCrMCH0hJ09lL6h5lSMp9EB0VStw9E2muAWtRvOfYA9OO9wdmI=
