os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - DOCKER_USERNAME=h3brandon
  - QUAYIO_USERNAME=h3brandon
  - secure: BhagWxyYZPO4M4zSz5N9pmHRaZCFIdP3ZdnL+ouWZ60vg/2n9g2Mc20X7lwYweJ1Oa4CFFIpGLLXbQdlD251aRnlkDCzCOSpyxOkRTCeRDiA+eInkby7k3t6G1+SC6Mc3BRksybueqc/uojJ1B70vzR7CJpiRWDkdxA6S6RrET48EPoG2i1yhlbH7t2bagtPkkZ5cheuX3ILWJJjzV6Dg0WTakqeN7a1srLwVJkq1qGcisejdD1G9XfIdZLB8lh0iATHa5M5VbJk2Iftuzx6y+dscO/8pRSat2NHlqHzTsgpmYSu4oegzCdfSPIUFtqU3VJQIhDzA+z7E6WwHPNvvsvLWG2byk+jTWjwvHxgjRb1zY96sL5v/eF1+FXKTFq65w5/wbQfC+AnmCaozta0gszlG0ZAYJTgOl0L8/RVOg61RxGVUi3MY9FfdDLnZnIQKW14bZ5nKPoijYLHrf36QXDGipplSsprEddUwoUo+LHHaP7LRBtxVcPLf+uTLSCXeyTpIM6aNLCpAfcBjme7VFPPxH/1LPJP5cQIBPXM3jDdToZ57BxbJSarcmcd0YKwKxv1fAr8boUO89CGP/zI8SHFfVUZO8x4EeUw2uMtaf8hxoUJB3TDjjpaxiwcogItmuyo5UUMaunheBomyXyQIn9tUFWppRURWETNy7JitnM=
  - secure: qlQvedTKLScwn7fuZO/S/GBWIRR946lWmWRTwDhw9vOjYAWyKncldGMpAceMoD1aP9AnHfCXHnoypRAz7D9bcbIsi3JMbj6wa6I4+cZ/v+SyB9Ddx+WNAJWuotyw5kySqAyqRg9VnSV/CfBx3l1pqD3JiHnT7sZjjjp2CdYBkAqnjr4+d//89TBtc2zD1PvWESKf9lWh0/iHbQuChmCZ9H57F2WqBvobZnn7nc1NgfVia7Msi5cb83xrEg27A3Y911Up7phbgX+Y/LUSDME/6iorjjS/0rnqfewG2w2dCjrj40s7NhuWRLkIlEjxN9McZR9dbh9Khsk2qxKiEv8+3dQ2i0f1jUr7pB3JK38S4RTO/2J5BC5onSbxO8c8rLWtVYpohXsPh7jHnSAOOrn6T50/rhSY6Io5tuRQJexSF9SDdKv7cOtICJm5lJTwRpxutdoeYIQDTFfYiT/TgqSq/uz2IuURaI45rwvmusSSfTGJM35+yn2xeBNDgC6GTDBtZyegnhunrC9uEGpiUHGc7MVbvKyhgoN64/C2kv9M7FmPXVS9UBQTVDQtRNY/JJISuMa3gyPMa2nskDXBQGLF0X4E5o/8e1+4AqqOl7w+NuzfkRlqR2OpJp8nT52ilYjsDFVwNk4deqWXvrkQuut7Mj4l8yGqQrGHbxgvB9mi24M=
