os: linux
dist: trusty
sudo: required
language: node_js
services:
- docker
jobs:
  include:
  - name: SAE Docs Bridge API
    stage: APIs
    language: node_js
    node_js: lts/*
    cache: npm
    before_install:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm ci
      if [ "$TRAVIS_TAG" = "" ]; then npm audit --production; fi
    before_script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      cp config/default.json.template config/default.json
    script:
    - |-
      cd /home/travis/build/bcgov/sae-docs-bridge
      npm test
      bash docker_quayio_push sae_docs_bridge
    before_deploy:
    - cd /home/travis/build/bcgov/sae-docs-bridge
    deploy:
      provider: script
      script: bash docker_push sae_docs_bridge || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"
env:
  global:
  - secure: cfc1ZNe18u22WXnv9jb4wML+LVllzCNfTD66TMfVn0AhKOqLoiqKCSu2bVaOzXlPT1uhcUCzzTRKh+D+IY/WzDQDoGTXdqUSYpkZCZkCF6SlW5fhSLNvHBSh0x+TeggYb9M7ZYZO2Hj4QByelQasoax8/zhkXW7vWjyWKNfjqV+f17SV9ba6xv9uNLK0ZNUlQECrWb4wPKF3m6dTKGeyKdzwL2lf3t7ciSoij7IxxAUKce6Jc0GXEXGlVQnhXWUIneoDOh1VMToHxYdWiK3gNES0iR6nPp+IpRYUlvNRwz2jlSBPKtJLMuRDTOoJs4vYVJCuOHPmf0mdPZttf5MxEGEhtM8V8H6iuOHBmKpCnk0f8VIWEY8Lyo7neE9TRDQ+QjvYuhp+7hNctAUq5AYaz5wWG/ZvWMENR9jxiezCWvbGm5lDRa5lXet5evlwJ8V9d9IUUhsYI+OnyWcbxqKpqvKKj3TgSB3C0HXz7bOSsz9+xvQNpT1FoItmwilvA+G+Xi2WGB0O+yGAb6EnUX+JdlfzMEJ/JidtekcxKQeabwkSevytLlpqF3ACGAKVFvR+KkxOxLOHQ9bd03oSP6bpvvhJIRlEf70fu3F3aRud7AuOckFwDf70qDcqMyLukUGUG0AKqFpryCN79GLS707yfF+H3s9kfRWx8iANvmpYcC4=
  - secure: IZ/G9X3gQJujkJ8/1ECEgBX8BKPLWXHVvColmqKXhWU0g7Oz6Etr3hOFnr0mA/kgeManO9E4mRYkWKwph6SKjLPLD+3o2SPCVTrVpdsw3h9XKR/LJJq3hAvYmaBX7RyhceVNjMKRyI/ZCBUEpZSj8zFIVXABg51nohLlAPfErDl0OgJ++VuTR578WYNR7l5UjsLyWu7wTH7Jy4jCyiV4BPxXYKFjRTUTMPuyhh5apUJ85Eewbnt4rNZBYQZ2HAcMgnsvV/cYM5ztGpwWjjP7GirVkL6x7zMxgnJdy3XLaFYfQ2g0ETs2sG09YSfUyM1fp96vZu4xrxrdFzdaCiEClRx6Y/18LpocWnxyskMTPNxdToG7LCm1ENmcSymBWKyxeUVCjPIXna1enf+ucNsMatlRa8GNTIv6HccHky6rZBOFOP6X//RAaKJvn5hSytsi7Hwrewvozq3Vhah17soXu69P2939tCYflBj0aUu+fOfeKBuT/2AY0ftWNWa2DEqaLvWmYIqjL+W1ZvroowfVAh0ATLxreChmD95XjClrxbgCMErrs69M0obH7VL8iMXUQvZaod1tWCIixIGLzeLitaGQLBdX0dZ0QVLNTfKEF7BDE0vuPOSZ4q2JnSA4FZ+VL2ilzPK1qKWTrcxOHAUGhIfutl7/ZlM7ZNjtjkFTG/c=
  - secure: Of8bbHynEzlIeQvfu0SpFPQya9A6ccMOHEujzWLBPM7g27QGcKzgEjfRNQ33JGKAWZ6N2xysl4+YDO5LXrn86ZKgOxfIJVrykXLj9uBsOpabSJXee7BEDwE9mXyPce67Ia5o4uoR4uh2s9H0WSK2Npl2+rJPegNk7V7AW7ppIBKCyQOvj38d0iFDBU1h75tIi2MvaK9QoOqQWEep0Jr64pPlfj6rgd2wsVooIYl+FKsIqYcHCMt3AR1ITUioRttARrZLdJNw724Tginzj29a2j4UW/24g9MvHWT5CTmd4/SF4zjixO23HPKTGS0eQBfAvVfMWFpv66gTva6zaS/Ilvrbt9M4lQshVZ9Mhw99RdScDA61LV8kBZDCb/tpV/CxWB2PGyFBUUFWYhokOF1CEBiM2UrPRMPvwEBRkmsAvbsT6y51hlDLTIcUyC7bDTgPz97FYlZ79eTwewbSikr+lGT+3C30z/d0neIiujqfCwHK6dnIzwqQx4AUFCTFEUh6SADVaaTcP1K1pHL8MQSpIbZNC0BxaaRHyb9EAzFA9MTbcVJXGNxjYiGAqnExKmaeQXEekZjTGVuSbehLtxqGYi9QKfY0KeF8DTtCss0xPnKjOXqeBBoUoUgs0nyECj2NqX7GEypPCerF7H+b0k2CpTG4kKuSe5UBsi720WkqQI4=
  - secure: Aaa75Sy/ApbDdb2uCxxr6uqwoj1MQf+bjAQl86SKgqi74VHN0qHpYfguC4iJMRkahioDjKAlPeXg5nFeQbHDCXFUVuKQO1fl6KtzbjSxB4XiobMrrEymMtVZB6a9bxVa/9SU96Hnv5BNUp2zdIrdjNozzAI0eoLg/tO6RqFpGslSOe+5fLTD1d9qVnV+JVHoGaQRXcRbmeBhItXfDvIUkqUIduSvx9GE1gfzD0cpfmHwYHAS6So+y/XK1rZu890s6+YgMcLEmWWBXtf3aL4TozwNhVkf1m+Ucp/zL1vZq2PqLD95WKLxtnmBhjZpe9Wt/Zo+34Z2HRq88GxqHZTg/Cfk31QGxWLLJzRRC6GC6h0tW3fe5fGRM4C0lOLa+1edTk5eOC48uMgJXiFoWvRZwOgBhd0EdHi/B36xiWkR7FugKZ5eplr1c7jcuRyifDMTxK8yNa+R+ditj7zty/n5aUTltxGos/27o9TFd2G5d1MA6+/Msms0NABZni3KFs1o88OZiW5mUFlnD9zcDTXfieLFvtu0IzbaNfYrJS0MQOWZmsFMTc3h0cX6NCVbEYlFAzquIiOdNH1YAi6IpJhJNwKqO/hQk1moXTmaxdXzifrFFFYjUZnsuU1M2SEaJP51+vhj3vMDJvCjdKzVdicsoIE3fEjQG5JM+xieeAxYFUA=
